# Generated by Django 2.2.6 on 2019-11-24 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('nombre_grupo', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('fecha_fundacion', models.DateTimeField(blank=True, null=True)),
                ('estilo_musical', models.CharField(max_length=30)),
                ('sitio_web', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Musico',
            fields=[
                ('nombre_musico', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('fecha_nacimiento', models.DateTimeField(blank=True, null=True)),
                ('instrumento_ppal', models.CharField(max_length=30)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='práctica_05.Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('titulo_album', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('distribuidora', models.CharField(max_length=100)),
                ('fecha_lanzamiento', models.DateTimeField(blank=True, null=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='práctica_05.Grupo')),
            ],
        ),
    ]
