# Generated by Django 2.2.6 on 2020-01-04 00:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('práctica_05', '0004_auto_20200104_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='origen_grupo_lat',
            field=models.FloatField(default='', validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grupo',
            name='origen_grupo_long',
            field=models.FloatField(default='', validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
            preserve_default=False,
        ),
    ]
