# Generated by Django 2.2.6 on 2020-01-04 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('práctica_05', '0005_auto_20200104_0021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupo',
            old_name='origen_grupo_lat',
            new_name='origen_grupo_latitude',
        ),
        migrations.RenameField(
            model_name='grupo',
            old_name='origen_grupo_long',
            new_name='origen_grupo_longitude',
        ),
    ]
