# Generated by Django 2.2.6 on 2020-01-04 00:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('práctica_05', '0008_auto_20200104_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='origen_grupo_lat',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AddField(
            model_name='grupo',
            name='origen_grupo_long',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
    ]
